server:
  port: 8080
spring:
  application:
    name: ddxy-system
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.58.135:8848
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.58.135:3306/dapl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 511321
  redis:
    host: 192.168.58.135
    port: 6379
    password: 511321
  cache:
    cache-names: redis_cache
    type: redis
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ddxy.system.pojo